# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], max_length=10, null=True, verbose_name='Пол')),
                ('url', models.URLField(blank=True, help_text='Где мы можем найти больше о Вас?', max_length=500, null=True, verbose_name='Домашняя страница')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Картинка Аватар')),
                ('description', models.TextField(blank=True, help_text='Расскажите о себе!', null=True, verbose_name='Описание')),
                ('manually_edited', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL, verbose_name='Social Profile')),
            ],
            options={
                'verbose_name': 'Social Profile',
                'verbose_name_plural': 'Social Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
