# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import socialprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=socialprofile.models.avatar_upload_to),
        ),
    ]
