# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialprofile', '0004_socialprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на аватар'),
        ),
    ]
