# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialprofile', '0008_auto_20170210_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Загрузка аватара'),
        ),
    ]
