# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privroom',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='privroom',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Приватность'),
        ),
        migrations.AlterField(
            model_name='privroom',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
