# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170604_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privroom',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
