# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170604_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privroom',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
