# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170604_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privroom',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Приватность'),
        ),
    ]
